# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self


variables:
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Deploy
  displayName: Deploy to Azure Container Instance
  jobs:
  - job: Deploy
    displayName: Deploy to Azure Container Instance
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Service Connection Name'
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create -g YourRGName --name mynodecont1 --image ImagePathRepo:$(tag) --dns-name-label devnodeapp --cpu 1 --memory 1 --registry-login-server RegLoginServer --registry-username RegUserName --registry-password RegPasswd  --ports 80

